#!/bin/sh
# hcom release installer (Linux x86_64 only).
#
# Reads a release manifest from the CDN (https://cdn.ffc-w.com/hcom/releases/),
# downloads the x86_64-unknown-linux-gnu tarball it names, verifies the archive
# against BOTH the manifest's sha256 and the published `.sha256` sidecar, and
# only then swaps the binary into ~/.local/bin/hcom, keeping the previous one at
# hcom.bak. Nothing downloaded is ever executed: the only fetched executable
# bytes are inside the verified tarball.
#
# The release publisher copies this file verbatim, with no rewrite, to
# releases/install.sh, and only for an exact stable vX.Y.Z tag (written after
# latest.json). There is no versioned copy: pinning a test tag or an old release
# is done by setting HCOM_RELEASE_TAG, never by fetching a per-tag copy of this
# script. The published copy keeps the default `latest` below, so it resolves
# latest.json. Keep the default the literal `latest` here and never commit a
# concrete version in its place.
#
# The CDN base is a CONSTANT below, not an environment variable. The manifest's
# own "url" field is checked against the URL this script derives and never
# fetched from, so a rewritten channel pointer cannot repoint a download at
# another host: it can only make this script refuse.
#
# The one environment variable this accepts is HCOM_RELEASE_TAG, which selects
# which release to install (an exact vX.Y.Z, or `latest` to read latest.json).
# It names a release, never a host, so it cannot redirect the download.
#
# Testing note: the fixture harness in tests/ substitutes a fake CDN by
# overriding `curl` on PATH, not by setting a variable here. That is deliberate
# - a test seam in the published copy would be a way to repoint every host that
# runs it.

set -eu

HCOM_RELEASE_TAG="${HCOM_RELEASE_TAG:-latest}"
CDN_BASE_URL="https://cdn.ffc-w.com/hcom/releases/"
TARGET_TRIPLE="x86_64-unknown-linux-gnu"

TMP=""
STAGED=""

cleanup() {
    [ -z "$STAGED" ] || rm -f "$STAGED"
    [ -z "$TMP" ] || rm -rf "$TMP"
}
trap cleanup EXIT

die() {
    printf 'hcom-installer: %s\n' "$1" >&2
    exit 1
}

need() {
    command -v "$1" >/dev/null 2>&1 || die "required command not found: $1"
}

need curl
need tar
need uname
need awk
if ! command -v sha256sum >/dev/null 2>&1 && ! command -v shasum >/dev/null 2>&1; then
    die "required command not found: sha256sum (or shasum)"
fi

hash_file() {
    if command -v sha256sum >/dev/null 2>&1; then
        sha256sum "$1"
    else
        shasum -a 256 "$1"
    fi
}

BASE="${CDN_BASE_URL%/}"
BASE="$BASE/"
if [ "$HCOM_RELEASE_TAG" = "latest" ]; then
    MANIFEST_URL="${BASE}latest.json"
else
    printf '%s' "$HCOM_RELEASE_TAG" | grep -Eq '^v[0-9]+\.[0-9]+\.[0-9]+$' ||
        die "HCOM_RELEASE_TAG must be 'latest' or a stable vX.Y.Z tag (got '$HCOM_RELEASE_TAG')"
    MANIFEST_URL="${BASE}${HCOM_RELEASE_TAG}/manifest.json"
fi

printf 'hcom-installer: reading release manifest %s\n' "$MANIFEST_URL"
MANIFEST_BODY=$(curl -fsSL --max-time 60 "$MANIFEST_URL") ||
    die "could not read the release manifest at $MANIFEST_URL"

# The manifest is machine-generated by the release publisher; parse tolerantly
# and validate every field read, so a malformed manifest can only abort here.
# The version is a stable vX.Y.Z tag - exactly what src/update.rs accepts.
FLAT=$(printf '%s' "$MANIFEST_BODY" | tr '\n' ' ')
VERSION=$(printf '%s' "$FLAT" | sed -n 's/.*"version" *: *"\([^"]*\)".*/\1/p')
# The manifest's own "url" is read only to CHECK it, never to fetch from: every
# download below is built from the fixed CDN base, the validated version and
# the known file name. A manifest that names any other URL is rejected instead
# of obeyed, so whoever can rewrite a channel pointer still cannot repoint a
# download at a host of their choosing.
DECLARED_URL=$(printf '%s' "$FLAT" | sed -n "s/.*\"$TARGET_TRIPLE\"[^{]*{[^}]*\"url\" *: *\"\([^\"]*\)\".*/\1/p")
MANIFEST_SHA256=$(printf '%s' "$FLAT" | sed -n "s/.*\"$TARGET_TRIPLE\"[^{]*{[^}]*\"sha256\" *: *\"\([^\"]*\)\".*/\1/p")

printf '%s' "$VERSION" | grep -Eq '^v[0-9]+\.[0-9]+\.[0-9]+$' ||
    die "release manifest names version '$VERSION', which is not a stable vX.Y.Z release"
[ -n "$DECLARED_URL" ] ||
    die "release manifest has no artifact for $TARGET_TRIPLE"
printf '%s' "$MANIFEST_SHA256" | grep -Eq '^[0-9a-fA-F]{64}$' ||
    die "release manifest has a malformed sha256 for $TARGET_TRIPLE"
MANIFEST_SHA256=$(printf '%s' "$MANIFEST_SHA256" | tr '[:upper:]' '[:lower:]')

TARBALL_NAME="hcom-$TARGET_TRIPLE.tar.gz"
ARTIFACT_URL="${BASE}${VERSION}/${TARBALL_NAME}"
[ "$DECLARED_URL" = "$ARTIFACT_URL" ] ||
    die "release manifest points $TARGET_TRIPLE at '$DECLARED_URL', but a release archive for $VERSION must be at '$ARTIFACT_URL' - not installing"

# Every other host is told how to build the release tag instead of being
# pointed at an archive that does not exist (Linux x86_64 is the only prebuilt).
OS=$(uname -s)
ARCH=$(uname -m)
if [ "$OS" != "Linux" ] || [ "$ARCH" != "x86_64" ]; then
    printf 'hcom-installer: no prebuilt hcom %s for %s-%s\n' "${VERSION#v}" "$ARCH" "$OS" >&2
    printf 'Install it from source instead:\n' >&2
    printf '  git clone --branch %s https://github.com/Michaelzag/hcom.git\n' "$VERSION" >&2
    printf '  cd hcom && cargo build --release --locked\n\n' >&2
    printf 'Release archives and the release manifest live at https://cdn.ffc-w.com/hcom/releases/\n' >&2
    exit 1
fi

# The published archive is glibc-linked, so what matters is whether THIS host
# can run a glibc binary - not whether it has musl. A glibc host with the musl
# runtime also installed can use the archive perfectly well, so probing for the
# musl loader would refuse a host that is fine. Probe for the glibc loader
# instead: the refusal is for a host that has no GNU dynamic loader at all, which
# is the case that would end up with an executable that cannot start.
GLIBC_LD="/lib/ld-linux-$(uname -m | sed 's/x86_64/x86-64/').so.2"
if [ ! -f "$GLIBC_LD" ] && [ ! -f /lib64/ld-linux-x86-64.so.2 ]; then
    printf 'hcom-installer: no GNU dynamic loader found on this host; the published\n' >&2
    printf 'archive is glibc-linked, so installing it would leave an executable that\n' >&2
    printf 'cannot start. Nothing was changed.\n' >&2
    printf 'Install it from source instead:\n' >&2
    printf '  git clone --branch %s https://github.com/Michaelzag/hcom.git\n' "$VERSION" >&2
    printf '  cd hcom && cargo build --release --locked\n\n' >&2
    printf 'Release archives and the release manifest live at https://cdn.ffc-w.com/hcom/releases/\n' >&2
    exit 1
fi

SIDECAR=$(curl -fsSL --max-time 60 "${ARTIFACT_URL}.sha256") ||
    die "could not download ${ARTIFACT_URL}.sha256"
# sha256sum -c format: `<64 hex>  <filename>` on the first line.
SIDECAR_SHA256=$(printf '%s\n' "$SIDECAR" | awk 'NR==1 { print $1 }')
printf '%s' "$SIDECAR_SHA256" | grep -Eq '^[0-9a-fA-F]{64}$' ||
    die "malformed sha256 sidecar at ${ARTIFACT_URL}.sha256 (expected sha256sum -c format)"
SIDECAR_SHA256=$(printf '%s' "$SIDECAR_SHA256" | tr '[:upper:]' '[:lower:]')

TMP=$(mktemp -d "${TMPDIR:-/tmp}/hcom-installer.XXXXXX") ||
    die "could not create a temporary directory"
TARBALL="$TMP/$(basename "$ARTIFACT_URL")"

printf 'hcom-installer: downloading %s\n' "$ARTIFACT_URL"
curl -fsSL --max-time 300 -o "$TARBALL" "$ARTIFACT_URL" ||
    die "could not download $ARTIFACT_URL"

ACTUAL_SHA256=$(hash_file "$TARBALL")
ACTUAL_SHA256=${ACTUAL_SHA256%% *}

# Both checks happen before anything is written outside the temporary
# directory: a corrupted or swapped download must never reach the swap.
[ "$SIDECAR_SHA256" = "$MANIFEST_SHA256" ] ||
    die "checksum mismatch: manifest sha256 $MANIFEST_SHA256 does not match sidecar sha256 $SIDECAR_SHA256 for $ARTIFACT_URL - not installing"
[ "$ACTUAL_SHA256" = "$SIDECAR_SHA256" ] ||
    die "checksum mismatch: $ARTIFACT_URL hashed to $ACTUAL_SHA256, expected $SIDECAR_SHA256 - not installing"

printf 'hcom-installer: sha256 verified (%s)\n' "$ACTUAL_SHA256"

tar -xzf "$TARBALL" -C "$TMP" "hcom-$TARGET_TRIPLE/hcom" ||
    die "release archive does not contain hcom-$TARGET_TRIPLE/hcom"
# -f alone is true for a symlink to a regular file, and the download URL is now
# built by us rather than read from the manifest, so a symlinked member would be
# defence in depth against a second-order path: refuse it explicitly.
[ -L "$TMP/hcom-$TARGET_TRIPLE/hcom" ] &&
    die "release archive member hcom-$TARGET_TRIPLE/hcom is a symlink, not a regular file"
[ -f "$TMP/hcom-$TARGET_TRIPLE/hcom" ] ||
    die "release archive did not unpack hcom-$TARGET_TRIPLE/hcom"

[ -n "${HOME:-}" ] || die "HOME is not set"
BIN_DIR="$HOME/.local/bin"
BIN="$BIN_DIR/hcom"
BAK="$BIN.bak"
STAGED="$BIN_DIR/.hcom-installer-new.$$"
# The SAME lock the Rust updater takes, on the same path, so this script and
# `hcom update` exclude each other as well as themselves. Without it two
# overlapping installs interleave in the swap below: one moves the live binary
# aside, the other deletes that same file, and the first restores it - leaving
# one backup, now the *new* bytes, for two callers that both reported success.
LOCK="$BIN_DIR/.hcom.update.lock"
LOCKED=0

release_lock() { [ "$LOCKED" -eq 0 ] || exec 9>&-; }

mkdir -p "$BIN_DIR" || die "could not create $BIN_DIR"

# The lock file is never deleted: removing a path another process may hold
# locked lets the next installer lock a fresh inode and stop excluding anybody.
# It is opened by path, so it is a real file and not something to follow.
if ! command -v flock >/dev/null 2>&1; then
    printf 'hcom-installer: required command not found: flock\n' >&2
    exit 1
fi
exec 9>>"$LOCK" || die "could not open $LOCK"
flock -w 120 9 || die "another install held $LOCK for more than 120s - not installing"
LOCKED=1

# On a signal the handler MUST exit. A handler that only cleaned up and
# returned would release the lock and then run the rest of the script - the
# swap below - with no mutual exclusion, which is the exact race the lock
# exists to prevent. Trapping the signal also means we choose the exit status
# instead of whatever the interrupted command happened to return.
on_signal() {
    signal=$1
    trap - INT TERM
    printf 'hcom-installer: interrupted by SIG%s - nothing was installed\n' "$signal" >&2
    cleanup
    release_lock
    exit 130
}
trap 'on_signal INT' INT
trap 'on_signal TERM' TERM
trap 'cleanup; release_lock' EXIT

cp "$TMP/hcom-$TARGET_TRIPLE/hcom" "$STAGED" || die "could not stage the new binary"
chmod 0755 "$STAGED" || die "could not make the new binary executable"

# The swap is the one part of this script that must not be interrupted. A
# handler that fired between "old binary moved aside" and "staged binary moved
# into place" would delete the staged file and exit with NO executable at all, so
# both signals are ignored for the duration rather than trapped. `mv` within one
# directory is a rename, so the window is two syscalls wide; the deferred signal
# is delivered after the swap completes, at which point stopping is correct.
trap '' INT TERM

# The old bytes move aside before the new ones take its place, so a failure
# half way through leaves a restorable executable rather than none. The new
# bytes were staged in the same directory first because rename across a
# filesystem boundary fails and a temporary directory usually is one.
if [ -e "$BIN" ]; then
    rm -f "$BAK"
    mv "$BIN" "$BAK" || die "could not move $BIN aside"
    if ! mv "$STAGED" "$BIN"; then
        mv "$BAK" "$BIN"
        die "could not replace $BIN (original restored)"
    fi
else
    mv "$STAGED" "$BIN" || die "could not install $BIN"
fi
STAGED=""

# The swap is done and the install is either complete or restored, so a signal
# can safely stop the script from here. It was ignored across the swap, and an
# ignored signal is DISCARDED rather than queued - so a cancellation that arrived
# mid-swap would otherwise be silently lost and the install would report success
# after the user asked it to stop. Re-arm the handler, then honour anything that
# arrived while it was off: the install is already done, so the honest outcome is
# to report it and exit nonzero rather than claim the signal was heeded.
INTERRUPTED=0
trap 'INTERRUPTED=1' INT
trap 'INTERRUPTED=TERM' TERM

release_lock

if [ "$INTERRUPTED" != 0 ]; then
    printf 'hcom-installer: interrupted during the swap; the install completed anyway\n' >&2
    exit 130
fi

printf 'hcom %s installed to %s\n' "${VERSION#v}" "$BIN"
if [ -e "$BAK" ]; then
    printf 'previous binary kept at %s\n' "$BAK"
fi
case ":$PATH:" in
*":$BIN_DIR:"*) ;;
*) printf 'note: %s is not on your PATH\n' "$BIN_DIR" >&2 ;;
esac
