#!/bin/sh
# hcom release installer (Linux x86_64 only).
#
# Reads a release manifest from the CDN (https://cdn.ffc-w.com/hcom/releases/),
# downloads the x86_64-unknown-linux-gnu tarball it names, verifies the archive
# against BOTH the manifest's sha256 and the published `.sha256` sidecar, and
# only then swaps the binary into ~/.local/bin/hcom, keeping the previous one at
# hcom.bak. Nothing downloaded is ever executed: the only fetched executable
# bytes are inside the verified tarball.
#
# The release publisher copies this file verbatim, with no rewrite, to
# releases/install.sh, and only for an exact stable vX.Y.Z tag (written after
# latest.json). There is no versioned copy: pinning a test tag or an old release
# is done by setting HCOM_RELEASE_TAG, never by fetching a per-tag copy of this
# script. The published copy keeps the default `latest` below, so it resolves
# latest.json. Keep the default the literal `latest` here and never commit a
# concrete version in its place.
#
# Environment overrides, for testing against a fixture instead of the live CDN:
#   HCOM_BASE_URL             release prefix
#                             (default https://cdn.ffc-w.com/hcom/releases/)
#   HCOM_RELEASE_TAG          release to install; `latest` reads latest.json,
#                             anything else reads <tag>/manifest.json
#                             (default `latest`)
#   HCOM_INSTALL_MANIFEST_URL manifest URL to read directly, highest precedence

set -eu

HCOM_RELEASE_TAG="${HCOM_RELEASE_TAG:-latest}"
HCOM_INSTALL_MANIFEST_URL="${HCOM_INSTALL_MANIFEST_URL:-}"
HCOM_BASE_URL="${HCOM_BASE_URL:-https://cdn.ffc-w.com/hcom/releases/}"
TARGET_TRIPLE="x86_64-unknown-linux-gnu"

TMP=""
STAGED=""

cleanup() {
    [ -z "$STAGED" ] || rm -f "$STAGED"
    [ -z "$TMP" ] || rm -rf "$TMP"
}
trap cleanup EXIT

die() {
    printf 'hcom-installer: %s\n' "$1" >&2
    exit 1
}

need() {
    command -v "$1" >/dev/null 2>&1 || die "required command not found: $1"
}

need curl
need tar
need uname
need awk
if ! command -v sha256sum >/dev/null 2>&1 && ! command -v shasum >/dev/null 2>&1; then
    die "required command not found: sha256sum (or shasum)"
fi

hash_file() {
    if command -v sha256sum >/dev/null 2>&1; then
        sha256sum "$1"
    else
        shasum -a 256 "$1"
    fi
}

if [ -n "$HCOM_INSTALL_MANIFEST_URL" ]; then
    printf '%s' "$HCOM_INSTALL_MANIFEST_URL" | grep -Eq '^(https?|file)://' ||
        die "HCOM_INSTALL_MANIFEST_URL must be an http://, https:// or file:// URL"
    MANIFEST_URL=$HCOM_INSTALL_MANIFEST_URL
else
    BASE="${HCOM_BASE_URL%/}"
    BASE="$BASE/"
    if [ "$HCOM_RELEASE_TAG" = "latest" ]; then
        MANIFEST_URL="${BASE}latest.json"
    else
        MANIFEST_URL="${BASE}${HCOM_RELEASE_TAG}/manifest.json"
    fi
fi

printf 'hcom-installer: reading release manifest %s\n' "$MANIFEST_URL"
MANIFEST_BODY=$(curl -fsSL --max-time 60 "$MANIFEST_URL") ||
    die "could not read the release manifest at $MANIFEST_URL"

# The manifest is machine-generated by the release publisher; parse tolerantly
# and validate every field read, so a malformed manifest can only abort here.
# The version is a stable vX.Y.Z tag - exactly what src/update.rs accepts.
FLAT=$(printf '%s' "$MANIFEST_BODY" | tr '\n' ' ')
VERSION=$(printf '%s' "$FLAT" | sed -n 's/.*"version" *: *"\([^"]*\)".*/\1/p')
ARTIFACT_URL=$(printf '%s' "$FLAT" | sed -n "s/.*\"$TARGET_TRIPLE\"[^{]*{[^}]*\"url\" *: *\"\([^\"]*\)\".*/\1/p")
MANIFEST_SHA256=$(printf '%s' "$FLAT" | sed -n "s/.*\"$TARGET_TRIPLE\"[^{]*{[^}]*\"sha256\" *: *\"\([^\"]*\)\".*/\1/p")

printf '%s' "$VERSION" | grep -Eq '^v[0-9]+\.[0-9]+\.[0-9]+$' ||
    die "release manifest names version '$VERSION', which is not a stable vX.Y.Z release"
[ -n "$ARTIFACT_URL" ] ||
    die "release manifest has no artifact for $TARGET_TRIPLE"
printf '%s' "$MANIFEST_SHA256" | grep -Eq '^[0-9a-fA-F]{64}$' ||
    die "release manifest has a malformed sha256 for $TARGET_TRIPLE"
MANIFEST_SHA256=$(printf '%s' "$MANIFEST_SHA256" | tr '[:upper:]' '[:lower:]')

# Every other host is told how to build the release tag instead of being
# pointed at an archive that does not exist (Linux x86_64 is the only prebuilt).
OS=$(uname -s)
ARCH=$(uname -m)
if [ "$OS" != "Linux" ] || [ "$ARCH" != "x86_64" ]; then
    printf 'hcom-installer: no prebuilt hcom %s for %s-%s\n' "${VERSION#v}" "$ARCH" "$OS" >&2
    printf 'Install it from source instead:\n' >&2
    printf '  git clone --branch %s https://github.com/Michaelzag/hcom.git\n' "$VERSION" >&2
    printf '  cd hcom && cargo build --release --locked\n\n' >&2
    printf 'Release archives and the release manifest live at https://cdn.ffc-w.com/hcom/releases/\n' >&2
    exit 1
fi

SIDECAR=$(curl -fsSL --max-time 60 "${ARTIFACT_URL}.sha256") ||
    die "could not download ${ARTIFACT_URL}.sha256"
# sha256sum -c format: `<64 hex>  <filename>` on the first line.
SIDECAR_SHA256=$(printf '%s\n' "$SIDECAR" | awk 'NR==1 { print $1 }')
printf '%s' "$SIDECAR_SHA256" | grep -Eq '^[0-9a-fA-F]{64}$' ||
    die "malformed sha256 sidecar at ${ARTIFACT_URL}.sha256 (expected sha256sum -c format)"
SIDECAR_SHA256=$(printf '%s' "$SIDECAR_SHA256" | tr '[:upper:]' '[:lower:]')

TMP=$(mktemp -d "${TMPDIR:-/tmp}/hcom-installer.XXXXXX") ||
    die "could not create a temporary directory"
TARBALL="$TMP/$(basename "$ARTIFACT_URL")"

printf 'hcom-installer: downloading %s\n' "$ARTIFACT_URL"
curl -fsSL --max-time 300 -o "$TARBALL" "$ARTIFACT_URL" ||
    die "could not download $ARTIFACT_URL"

ACTUAL_SHA256=$(hash_file "$TARBALL")
ACTUAL_SHA256=${ACTUAL_SHA256%% *}

# Both checks happen before anything is written outside the temporary
# directory: a corrupted or swapped download must never reach the swap.
[ "$SIDECAR_SHA256" = "$MANIFEST_SHA256" ] ||
    die "checksum mismatch: manifest sha256 $MANIFEST_SHA256 does not match sidecar sha256 $SIDECAR_SHA256 for $ARTIFACT_URL - not installing"
[ "$ACTUAL_SHA256" = "$SIDECAR_SHA256" ] ||
    die "checksum mismatch: $ARTIFACT_URL hashed to $ACTUAL_SHA256, expected $SIDECAR_SHA256 - not installing"

printf 'hcom-installer: sha256 verified (%s)\n' "$ACTUAL_SHA256"

tar -xzf "$TARBALL" -C "$TMP" "hcom-$TARGET_TRIPLE/hcom" ||
    die "release archive does not contain hcom-$TARGET_TRIPLE/hcom"
[ -f "$TMP/hcom-$TARGET_TRIPLE/hcom" ] ||
    die "release archive did not unpack hcom-$TARGET_TRIPLE/hcom"

[ -n "${HOME:-}" ] || die "HOME is not set"
BIN_DIR="$HOME/.local/bin"
BIN="$BIN_DIR/hcom"
BAK="$BIN.bak"
STAGED="$BIN_DIR/.hcom-installer-new.$$"

mkdir -p "$BIN_DIR" || die "could not create $BIN_DIR"
cp "$TMP/hcom-$TARGET_TRIPLE/hcom" "$STAGED" || die "could not stage the new binary"
chmod 0755 "$STAGED" || die "could not make the new binary executable"

# The old bytes move aside before the new ones take their place, so a failure
# half way through leaves a restorable executable rather than none. The new
# bytes were staged in the same directory first because rename across a
# filesystem boundary fails and a temporary directory usually is one.
if [ -e "$BIN" ]; then
    rm -f "$BAK"
    mv "$BIN" "$BAK" || die "could not move $BIN aside"
    if ! mv "$STAGED" "$BIN"; then
        mv "$BAK" "$BIN"
        die "could not replace $BIN (original restored)"
    fi
else
    mv "$STAGED" "$BIN" || die "could not install $BIN"
fi
STAGED=""

printf 'hcom %s installed to %s\n' "${VERSION#v}" "$BIN"
if [ -e "$BAK" ]; then
    printf 'previous binary kept at %s\n' "$BAK"
fi
case ":$PATH:" in
*":$BIN_DIR:"*) ;;
*) printf 'note: %s is not on your PATH\n' "$BIN_DIR" >&2 ;;
esac
